### ISSUE TITLE
可视化代码

### ISSUE THREAD

**Issue by OneIsAll-w** [lumingzzz/TIC#3]
作者您好，我对您的这个工作很感兴趣，请问作者能否提供下论文中有关潜在特征的紧凑程度可视化的代码，十分感谢！

**Comment by lumingzzz** [comment]
您好，
可视化的代码不是太好找了，不过也不复杂，可以仿照torchCAM的做法对latent上某一个点求输入对其的梯度即可，或者chatGPT老师可以帮你直接写一个样例。
