### ISSUE TITLE
训练集和预训练模型相关问题

### ISSUE THREAD

**Issue by CodingLuweir** [lumingzzz/TIC#4]
作者，您好！

请问训练集是将 The Flicker 2W 训练集中每张图片随机裁剪成3张 256*256 大小的图片，还是随机裁剪成一张 256*256 大小的图片？
以及有没有预训练模型可以用来进行实验对比？

谢谢！

**Comment by lumingzzz** [comment]
您好，是在训练过程中随机裁剪成256x256大小的图片；由于是阶段性结果，预训练模型没有再作保留，只保留了测试结果。
